name: generate-site

# Only run this when main branch changes
on:
  push:
    branches:
      - main
    paths:
      - src/**
  
  # Run manually
  workflow_dispatch:

jobs:
  generate-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Import environment variables
        id: dotenv
        uses: falti/dotenv-action@v1.0.2

      # Install Python
      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      
      - name: Install Python dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt
      
      - name: Build site using Docbro
        env:
          BASE_URL: ${{ steps.dotenv.outputs.base_url }}
          PROJECT_NAME: ${{ steps.dotenv.outputs.project_name }}
        run: |
          python docbro.py src/
      
      - name: Github Pages Action for Project
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./docs/
          destination_dir: ${{ steps.dotenv.outputs.version }}
      
      - name: Build versions index.html
        env:
          GITHUB_USERNAME: ${{ steps.dotenv.outputs.github_username }}
          GITHUB_REPO: ${{ steps.dotenv.outputs.github_repo }}
        run: |
          python generate_version_html.py
        
      - name: Github Pages Action for Versions
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./top-level/
          keep_files: true